import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const canvas=document.querySelector('#cinema'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,120);camera.position.z=8;scene.add(new THREE.AmbientLight(0xffead5,1.5));const key=new THREE.PointLight(0xffad69,55);key.position.set(3,3,5);scene.add(key);
const beanGeo=new THREE.SphereGeometry(.18,20,14);beanGeo.scale(1,.58,.42);const beans=[];for(let i=0;i<210;i++){const m=new THREE.Mesh(beanGeo,new THREE.MeshStandardMaterial({color:new THREE.Color().setHSL(.055,.62,.13+Math.random()*.09),roughness:.58}));m.userData={a:Math.random()*Math.PI*2,r:2+Math.random()*8,z:-18+Math.random()*30,s:.25+Math.random()*1.45,spd:.25+Math.random()*.75};scene.add(m);beans.push(m)}
const streamMat=new THREE.MeshPhysicalMaterial({color:0x713318,roughness:.25,metalness:.03});const milkMat=new THREE.MeshPhysicalMaterial({color:0xf2dfbd,roughness:.32});function tube(mat,off){const c=new THREE.CatmullRomCurve3([new THREE.Vector3(-9,-3+off,-7),new THREE.Vector3(-4,2+off,-4),new THREE.Vector3(0,-1+off,-1),new THREE.Vector3(4,2+off,2),new THREE.Vector3(9,-2+off,6)]);const m=new THREE.Mesh(new THREE.TubeGeometry(c,140,.18,12,false),mat);scene.add(m);return m}const coffee=tube(streamMat,.2),milk=tube(milkMat,-.45);
const ice=[];const ig=new THREE.BoxGeometry(.55,.55,.55),im=new THREE.MeshPhysicalMaterial({color:0xdff8ff,transparent:true,opacity:.34,transmission:.55,roughness:.05});for(let i=0;i<24;i++){let m=new THREE.Mesh(ig,im);m.userData={x:(Math.random()-.5)*10,y:(Math.random()-.5)*8,z:-8+Math.random()*16};scene.add(m);ice.push(m)}
let cur=0,start=performance.now(),beats=[...document.querySelectorAll('.beat')],cup=document.querySelector('#cup');
function render(t){const max=document.documentElement.scrollHeight-innerHeight,target=max?scrollY/max:0;cur+=(target-cur)*.055;const p=cur,time=(t-start)/1000;
camera.position.x=Math.sin(p*Math.PI*4)*.7+Math.sin(time*.25)*.12;camera.position.y=Math.cos(p*Math.PI*3)*.35;camera.position.z=8-Math.sin(p*Math.PI)*2.0;camera.rotation.z=Math.sin(p*Math.PI*6)*.018;
beans.forEach((m,i)=>{let d=m.userData,u=(d.a+time*d.spd+p*18);let tunnel=1+Math.sin(p*Math.PI)*.45;m.position.x=Math.cos(u)*d.r*tunnel;m.position.y=Math.sin(u*.73)*d.r*.55;m.position.z=((d.z+p*34+time*d.spd*1.4+18)%36)-18;let near=THREE.MathUtils.clamp((m.position.z+18)/20,.35,2.7),s=d.s*near;m.scale.set(s,s*.65,s*.5);m.rotation.x+=.012*d.spd;m.rotation.y+=.018*d.spd;m.rotation.z+=.009});
const liquid=THREE.MathUtils.smoothstep(p,.35,.66);coffee.visible=p>.32&&p<.72;milk.visible=p>.39&&p<.72;coffee.rotation.z=p*4+time*.12;milk.rotation.z=-p*3.4-time*.1;coffee.scale.setScalar(.8+liquid*.55);milk.scale.setScalar(.8+liquid*.55);
ice.forEach((m,i)=>{m.visible=p>.40&&p<.67;let d=m.userData;m.position.set(d.x+Math.sin(time+i)*.35,d.y+Math.cos(time*.7+i)*.25,((d.z+p*24+i*.2+9)%18)-9);m.rotation.x+=.01;m.rotation.y+=.014});
let x=Math.sin(p*Math.PI*3.2)*Math.min(innerWidth*.17,220),y=Math.cos(p*Math.PI*4)*Math.min(innerHeight*.08,65),scale=.78+Math.sin(p*Math.PI)*.48;cup.style.transform='translate(-50%,-50%) translate3d('+x+'px,'+y+'px,0) rotate('+Math.sin(p*Math.PI*5)*8+'deg) scale('+scale+')';cup.style.opacity=String(p>.93?Math.max(.25,1-(p-.93)*6):1);
document.querySelectorAll('.steam').forEach((s,i)=>s.style.transform='rotate('+(Math.sin(time*1.2+i)*10)+'deg) scaleY('+(1+Math.sin(time+i)*.12)+')');
beats.forEach(b=>b.classList.toggle('active',p>=+b.dataset.a&&p<=+b.dataset.b));document.querySelector('.progress i').style.height=(p*100)+'%';renderer.render(scene,camera);requestAnimationFrame(render)}requestAnimationFrame(render);
addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()});document.querySelector('#navToggle').onclick=()=>document.querySelector('.navlinks').classList.toggle('open');document.querySelectorAll('[data-jump]').forEach(a=>a.onclick=e=>{e.preventDefault();scrollTo({top:(document.documentElement.scrollHeight-innerHeight)*+a.dataset.jump,behavior:'smooth'});document.querySelector('.navlinks').classList.remove('open')});