import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const canvas=document.querySelector('#cinema'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,100);camera.position.z=8;
scene.add(new THREE.AmbientLight(0xffffff,1.7));const key=new THREE.PointLight(0xffc48b,45);key.position.set(3,3,4);scene.add(key);
const beanGeo=new THREE.SphereGeometry(.16,18,12);beanGeo.scale(1,.62,.45);const beanMat=new THREE.MeshStandardMaterial({color:0x512713,roughness:.62,metalness:.08});
const beans=new THREE.Group();scene.add(beans);
const beanStreams=[
 {curve:new THREE.CatmullRomCurve3([new THREE.Vector3(-9,-3,-12),new THREE.Vector3(-5,1,-8),new THREE.Vector3(-2,2,-4),new THREE.Vector3(1,.7,-1),new THREE.Vector3(4,-1,2),new THREE.Vector3(9,2,7)]),count:105,phase:0},
 {curve:new THREE.CatmullRomCurve3([new THREE.Vector3(9,3,-14),new THREE.Vector3(5,-1,-9),new THREE.Vector3(2,-2,-5),new THREE.Vector3(-1,-.5,-1),new THREE.Vector3(-4,2,3),new THREE.Vector3(-9,-1,8)]),count:90,phase:.34},
 {curve:new THREE.CatmullRomCurve3([new THREE.Vector3(-7,5,-15),new THREE.Vector3(-3,3,-10),new THREE.Vector3(0,-2,-6),new THREE.Vector3(2,-1,-2),new THREE.Vector3(1,3,2),new THREE.Vector3(7,5,9)]),count:75,phase:.67}
];
beanStreams.forEach((stream,si)=>{stream.items=[];for(let i=0;i<stream.count;i++){let m=new THREE.Mesh(beanGeo,beanMat.clone());m.material.color.offsetHSL(0,0,(Math.random()-.5)*.09);let s=.32+Math.random()*1.25;m.scale.set(s,s*.72,s*.55);m.userData={u:i/stream.count,jitter:new THREE.Vector3((Math.random()-.5)*1.15,(Math.random()-.5)*1.0,(Math.random()-.5)*.55),spin:new THREE.Vector3(.008+Math.random()*.02,.012+Math.random()*.025,.006+Math.random()*.018),s};beans.add(m);stream.items.push(m)}});const iceMat=new THREE.MeshPhysicalMaterial({color:0xdaf8ff,transparent:true,opacity:.38,roughness:.05,transmission:.6,thickness:.8});const iceGeo=new THREE.BoxGeometry(.55,.55,.55);const ice=new THREE.Group();scene.add(ice);for(let i=0;i<16;i++){let m=new THREE.Mesh(iceGeo,iceMat);m.position.set((Math.random()-.5)*9,(Math.random()-.5)*7,-5+Math.random()*11);m.rotation.set(Math.random()*3,Math.random()*3,0);m.userData={x:m.position.x,y:m.position.y,z:m.position.z};ice.add(m)}
function ribbon(color,y,z){let curve=new THREE.CatmullRomCurve3([new THREE.Vector3(-7,y,z),new THREE.Vector3(-3,y+1,z+.5),new THREE.Vector3(0,y-.8,z+1),new THREE.Vector3(3,y+.8,z+.3),new THREE.Vector3(7,y,z)]);let g=new THREE.TubeGeometry(curve,100,.22,12,false);let mat=new THREE.MeshPhysicalMaterial({color,roughness:.28,metalness:.02});let m=new THREE.Mesh(g,mat);scene.add(m);return m}const coffee=ribbon(0x6b2d12,.3,-.4),cream=ribbon(0xf1dfbd,-.35,.2);
const product=document.querySelector('#product'),beats=[...document.querySelectorAll('.beat')];let cur=0,start=performance.now();
function loop(t){let max=document.documentElement.scrollHeight-innerHeight,target=max?scrollY/max:0;cur+=(target-cur)*.065;let p=cur,time=(t-start)/1000;
camera.position.x=Math.sin(time*.35)*.24+Math.sin(p*Math.PI*5)*.42;camera.position.y=Math.cos(time*.28)*.15;camera.position.z=8-Math.sin(p*Math.PI)*1.25;camera.rotation.z=Math.sin(time*.25)*.008;
beanStreams.forEach((stream,si)=>stream.items.forEach((m,i)=>{let d=m.userData,u=(d.u+time*(.055+si*.012)+p*.58+stream.phase)%1;let pt=stream.curve.getPointAt(u),tan=stream.curve.getTangentAt(u),breath=.55+Math.sin(u*Math.PI)*1.25;let swirl=time*1.25+i*.73+si*2.1;m.position.copy(pt);m.position.x+=d.jitter.x*breath+Math.sin(swirl)*.32;m.position.y+=d.jitter.y*breath+Math.cos(swirl*.87)*.28;m.position.z+=d.jitter.z;m.rotation.x+=d.spin.x;m.rotation.y+=d.spin.y;m.rotation.z+=d.spin.z;let near=THREE.MathUtils.clamp((pt.z+15)/18,.45,2.25),sc=d.s*near;m.scale.set(sc,sc*.72,sc*.55);m.lookAt(pt.clone().add(tan));m.rotateZ(swirl*.08)}));
ice.visible=p>.3&&p<.68;ice.children.forEach((m,i)=>{let d=m.userData;m.position.z=d.z+((p*24+i*.45)%15)-7;m.position.x=d.x+Math.sin(time+i)*.3;m.position.y=d.y+Math.cos(time*.8+i)*.25;m.rotation.x+=.012;m.rotation.y+=.016});
coffee.rotation.z=Math.sin(time*.45)*.16+p*2.1;cream.rotation.z=-Math.sin(time*.38)*.14-p*1.7;coffee.position.z=Math.sin(p*Math.PI*3)*1.2;cream.position.z=Math.cos(p*Math.PI*3)*1.1;
let zoom=1+Math.sin(time*.55)*.025+p*.18;product.style.transform='translate(-50%,-50%) translate3d('+Math.sin(time*.45)*16+'px,'+Math.cos(time*.38)*10+'px,0) rotate('+Math.sin(time*.25)*1.2+'deg) scale('+zoom+')';product.style.opacity=String(Math.max(.32,1-p*.5));
beats.forEach(b=>b.classList.toggle('active',p>=+b.dataset.a&&p<=+b.dataset.b));renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);
addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()});
document.querySelector('#enter').onclick=()=>scrollTo({top:innerHeight*1.5,behavior:'smooth'});document.querySelector('#navToggle').onclick=()=>document.querySelector('.navlinks').classList.toggle('open');document.querySelectorAll('[data-jump]').forEach(a=>a.onclick=e=>{e.preventDefault();scrollTo({top:(document.documentElement.scrollHeight-innerHeight)*+a.dataset.jump,behavior:'smooth'})});