const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const world=q('#world'),hero=q('#heroBean'),cup=q('#cup'),portal=q('#portal'),espresso=q('.espresso'),milk=q('.milk'),progress=q('.progress i'),scenes=qa('.scene'),beanWrap=q('#beans'),iceWrap=q('#ice');
const beans=[];for(let i=0;i<(innerWidth<700?26:48);i++){let e=document.createElement('i');e.className='bean';let d={z:Math.random()*900-450,r:Math.random()*360,s:.45+Math.random()*1.8};e.style.left=Math.random()*100+'%';e.style.top=Math.random()*100+'%';beanWrap.append(e);beans.push([e,d])}
const ice=[];for(let i=0;i<(innerWidth<700?6:10);i++){let e=document.createElement('i');e.className='iceCube';let d={z:Math.random()*600-300,r:Math.random()*180,s:.5+Math.random()*1.4};e.style.left=5+Math.random()*90+'%';e.style.top=8+Math.random()*80+'%';iceWrap.append(e);ice.push([e,d])}
let cur=0;function frame(){let max=document.documentElement.scrollHeight-innerHeight,t=max?scrollY/max:0;cur+=(t-cur)*.075;let p=cur;progress.style.height=p*100+'%';world.style.transform='scale('+(1+Math.sin(p*Math.PI)*.055)+')';
beans.forEach(([e,d],i)=>{let burst=clamp((p-.07)/.17),z=d.z+burst*(650+(i%7)*55)-p*340;e.style.opacity=clamp(1-Math.abs(p-.5)*.55);e.style.transform='translate3d('+Math.sin(p*8+i)*55+'px,'+Math.cos(p*6+i)*35+'px,'+z+'px) rotate('+(d.r+p*600)+'deg) scale('+d.s+')'});
hero.style.opacity=clamp(1-clamp((p-.19)/.08));hero.style.transform='translate3d(0,0,'+clamp(p/.18)*600+'px) rotate('+p*220+'deg) scale('+(1+p*3.2)+')';
let li=clamp((p-.20)/.16),lo=1-clamp((p-.39)/.08);espresso.style.opacity=li*lo;milk.style.opacity=li*lo;espresso.style.transform='translateX('+(-25+45*li)+'%) rotate('+(-16+12*li)+'deg) skewX(-20deg) scaleY('+(.4+li)+')';milk.style.transform='translateX('+(25-40*li)+'%) rotate('+(18-12*li)+'deg) skewX(25deg) scaleY('+(.4+li)+')';
ice.forEach(([e,d],i)=>{let a=clamp((p-.34)/.08)*(1-clamp((p-.53)/.08)),z=d.z+(p-.34)*1800;e.style.opacity=a*.8;e.style.transform='translate3d('+Math.sin(p*10+i)*80+'px,'+Math.cos(p*9+i)*50+'px,'+z+'px) rotateX('+(d.r+p*500)+'deg) rotateY('+(d.r+p*700)+'deg) scale('+d.s+')'});
let ca=clamp((p-.40)/.1)*(1-clamp((p-.92)/.08));cup.style.opacity=ca;cup.style.transform='scale('+(.5+clamp((p-.4)/.12)*.65)+') rotateY('+Math.sin(p*10)*8+'deg)';
let po=clamp((p-.82)/.08)*(1-clamp((p-.965)/.03));portal.style.opacity=po;portal.style.transform='scale('+(1+clamp((p-.84)/.1)*9)+')';scenes.forEach(s=>s.classList.toggle('active',p>=+s.dataset.a&&p<=+s.dataset.b));requestAnimationFrame(frame)}requestAnimationFrame(frame);
q('#enter').onclick=()=>scrollTo({top:innerHeight*.9,behavior:'smooth'});q('#again').onclick=()=>scrollTo({top:0,behavior:'smooth'});q('#navToggle').onclick=()=>q('.navlinks').classList.toggle('open');